---
title: "Pipeline"
output:
  html_document:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Load tutorial data and annotation  
```{r}
setwd('/home/lijingyu/art/')
load('tutorial_data.Rdata')
```
# source the function
```{r}
source('scART.R')
source('function.R')
```

# Create the scART object, impute missing value and filter data
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
art<-CreatescART(data,metadata = annotation)  #metadata = annotation)
art<-RunImputation(art,k=1)
art<-SparseFilter(art, ncell=2, ncell2=0.8, ncell3=2, nbin=10)
```
# Reduce Dimensionality 
```{r include=FALSE}
art<-RunSim(art)
art<-DimReduce(art)
set.seed(10) 
art<-RunTSNE(art, nSV=20, ndims=2, perplexity=30)
art<-RunUMAP(art)
```
# Group cells into clusters, you can take a good look at the output pdf to adjust 'rho_cutoff' and 'delta_cutoff'
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
art<-RunCluster(art,delta_cutoff = 4,rho_cutoff = 8)
```
# Visualize an Embedding
```{r}
p1<-Visualization_2D(art,reductions = 'UMAP')#,anno = 'cell_type'
p2<-Visualization_2D(art,reductions = 'TSNE')
library(patchwork)
p1|p2

```
# Run and plot trajectory
```{r}
art<-RunTrajectory(art,anno='cell_type',nSV <- 20,ndim <- 10,gamma <- 10)
plotTrajectory(art)
```

# Create cell-gene matrix and explore gene chromtin accessibility
```{r}
art<-MapBin2Gene(art,Org = 'hg19')
PlotSelectGenesATAC(art,gene2plot = c('CDKN2C','BEND5'))  

```
```{r}
art<-RunChromVAR(art,Org=c('hg19'),species = c("Homo sapiens") ,min.count=1)
### min.count:the threshold of a peaks found at at least 10 cells

```

